---
- name: Windows - Descarga de instalador
  win_get_url:
    url: "{{ ssm_agent_url }}"
    dest: "C:\\Windows\\Temp\\{{ ssm_agent_file }}"
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"

- name: Windows - Instalar agente
  win_package:
    path: "C:\\Windows\\Temp\\{{ ssm_agent_file }}"
    product_id: "{{ win_product_id }}"
    arguments:
      - /install
      - /quiet
      - /norestart
    # state: present
  register: result_exe_install
  when: not ansible_check_mode

- name: Windows - Mostrar resultado de instalacion
  debug:
    var: result_exe_install
  when: result_exe_install.failed | default(false)
