---
- name: Crear directorio de personalizacion Systemd para el agente
  file:
    path: /etc/systemd/system/amazon-ssm-agent.service.d
    state: directory
    owner: root
    group: root
    mode: 0755
  become: true

- name: Crear configuracion personalizada Systemd para el agente
  template:
    src: override.conf.j2
    dest: /etc/systemd/system/amazon-ssm-agent.service.d/override.conf
    owner: root
    group: root
    mode: 0644
  become: true
  notify:
    - systemd-reload
    - amazon-ssm-agent-reload
