---
- name: Linux - Detener agente
  service:
    name: "{{ service_name }}"
    state: stopped
  become: true

- name: Linux - Invocar desinstalador para gestor de paquetes {{ ssm_pkg_type }}
  include_tasks: "{{ ssm_pkg_type }}-uninstall.yml"

- name: Linux - Eliminar directorios usados por el agente
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/systemd/system/amazon-ssm-agent.service.d/
    - /var/lib/amazon/ssm
    - /etc/amazon/ssm
  become: true
