---
- name: Ejecutar tareas previas
  include_tasks: pre-tasks.yml

- name: Invocar instalador en {{ ansible_system }} para gestor de paquetes {{ ssm_pkg_type }}
  include_tasks: "{{ ssm_pkg_type }}-install.yml"
  when: role_action == 'install'

- name: Invocar tareas post-instalacion
  include_tasks: post-install.yml
  when: role_action == 'install'

- name: Invocar desinstalador
  include_tasks: uninstall.yml
  when: role_action == 'uninstall'
