---
- name: Agregar entrada en /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ item.ip }} {{ item.hostname }}"
    state: present
  become: true
  loop: "{{ vault_nodes }}"
  when: vault_nodes is defined
