---
# tasks file for ansible-role-vault-raft
- name: Incluir tareas de configuraciones previas
  ansible.builtin.include_tasks: pre-config.yml

- name: Incluir tareas de instalacion de paquetes
  ansible.builtin.include_tasks: install.yml

- name: Incluir tareas de configuracion
  ansible.builtin.include_tasks: config.yml
