---
- name: Incluir tareas de configuraciones previas
  ansible.builtin.include_tasks: tasks-pre-config.yml

- name: Incluir tareas de instalacion de paquetes
  ansible.builtin.include_tasks: tasks-install.yml

- name: Incluir tareas de configuracion
  ansible.builtin.include_tasks: tasks-config.yml
