---
# handlers file for ansible-role-vault-raft
- name: Reiniciar Vault
  ansible.builtin.service:
    name: vault
    enabled: true
    state: restarted
  become: true
  listen: restart-vault

- name: Actualizar base de datos de certificados de confianza
  ansible.builtin.command: update-ca-certificates
  become: true
  listen: update-ca-certificates
