---
# handlers file for ansible-role-amazon-ssm-agent
- name: Recargar systemd
  command: systemctl daemon-reload
  become: true
  listen: systemd-reload

- name: Recargar agente
  service:
    name: "{{ service_name }}"
    state: restarted
    enabled: true
  become: true
  listen: amazon-ssm-agent-reload
