---
- name: Test role
  hosts: all
  gather_facts: false
  vars:
    server_common_name: angel.rengifo.com
    server_cert_file: ~/angel.rengifo.com.crt
    server_key_file: ~/angel.rengifo.com.key
    server_sans:
      - "DNS: angel.rengifo.pe"
    ca_cert_file: ~/ca.crt
    ca_key_file: ~/ca.key
  roles:
    - pki
