---
- name: Test role
  hosts: all
  gather_facts: false
  vars:
    copy_files_from: /home/arengifo
    package: vault-enterprise
    version: 1.15.4+ent-1
    license_file: /opt/vault/license.hclic
    tls_ca_file: /opt/vault/tls/ca.crt
    tls_cert_file: /opt/vault/tls/vault.sfi-networks.com.crt
    tls_key_file: /opt/vault/tls/vault.sfi-networks.com.key
    storage_backend: raft
    nodes:
      - 192.168.3.60 vault4.sfi-networks.com
      - 192.168.3.61 vault5.sfi-networks.com
      - 192.168.3.62 vault6.sfi-networks.com
    seal: awskms
    aws_region: us-east-1
    aws_kms_key_id: ae9d5e6e-05c2-4d5f-baae-7d653742aa2d
  roles:
    - vault-server
